config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, :content, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.create(article_params)
    redirect_to articles_path
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<div class="mx-auto mt-5 col-8">
  <%= simple_form_for(@article) do |f| %>
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.submit "#{@article.new_record? ? 'Create Article' : 'Update Article' }", class: "btn btn-primary btn-lg mx-auto d-block" %>
  <% end %>
</div>

app/views/articles/edit.html.erb
<%= render "form", article: @article %>

app/views/articles/index.html.erb
<div class="col-8 col-md-12 mx-auto">
  <% @articles.each_with_index do |article, idx| %>
    <%= link_to article do %>
      <div class="card my-3 <%= idx.odd? ? 'border-primary' : 'text-white bg-primary' %>">
        <div class="card-header h2"> <%= article.title %> </div>
        <div class="card-body <%= 'text-primary' if idx.odd? %> ">
          <p class="card-text text-truncate"> <%= article.content %> </p>
        </div>
        <div class="card-footer"><small>Last updated : <%= article.updated_at %> </small></div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/articles/new.html.erb
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<div class="col-8 col-md-12 mx-auto">
  <div class="card my-3 border-primary">
    <div class="card-header h2 d-flex justify-content-between">
      <%= @article.title %>
      <div>
        <%= link_to icon('fas', 'edit'), edit_article_url %>
        <%= link_to icon('fas', 'trash-alt'), @articles, method: :delete %>
      </div>
    </div>
    <div class="card-body">
      <p class="card-text"> <%= @article.content %> </p>
    </div>
    <div class="card-footer"><small>Last updated : <%= @article.updated_at %> </small></div>
  </div>
</div>

<%= link_to "Back to list", articles_path, class: "w-25 btn btn-primary btn-lg mx-auto d-block" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-primary justify-content-between">
      <%= link_to "Wikinimous", articles_path, class: "navbar-brand mb-0 h1" %>
      <% if params[:action] == "index" %>
        <%= link_to "Write New Article", new_article_url, class: "btn btn-outline-light my-2 my-sm-0" %>
      <% end %>
    </nav>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>